### ISSUE TITLE
Publish scaldi-akka on maven central

### ISSUE THREAD

**Issue by otrosien** [scaldi/scaldi-akka#4]
scaldi 0.6.0 has been published but not scaldi-akka. Can you please push this artifact as well? Thanks.

**Comment by dave-handy** [comment]
I can do that... I am a big fan of scaldi, and I also use akka, but I have never really understood the value proposition for scaldi-akka. In other words, can't you just do:
`bind[ActorRef[Foo]] to system.spawn(...)` and `inject[ActorRef[Foo]]` ?

... is this only useful for untyped actors..?

**Comment by otrosien** [comment]
Thanks for the reply. We'll do that instead for the time being.

**Comment by dave-handy** [comment]
So you are using typed actors..? If so, did you pull in this plugin before you converted to typed..? Trying to understand what value this plugin offers so I can maintain it properly.
